-- 코드를 작성해주세요
WITH RECURSIVE TREE AS (
    SELECT ID, 1 AS `LEVEL`
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, P.LEVEL + 1 AS `LEVEL`
    FROM ECOLI_DATA C JOIN TREE P ON C.PARENT_ID = P.ID
)

SELECT ID
FROM TREE
WHERE `LEVEL` = 3;