-- 코드를 작성해주세요
WITH RECURSIVE TREE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, P.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA C JOIN TREE P ON C.PARENT_ID = P.ID
)

SELECT COUNT(*) AS COUNT, P.GENERATION
FROM TREE P LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY P.GENERATION